package com.yukisoffd.lyracode

import com.yukisoffd.lyracode.data.AppSettings
import java.util.Locale

internal object UiTextBridge {
    @Volatile
    var languageMode: String = AppSettings.LANGUAGE_SYSTEM

    private val translations: Map<String, String> = mapOf(
        "Lyra 用户" to "Lyra User",
        "头像和昵称可在侧边栏顶部点击编辑。" to "Tap the profile card in the drawer to edit your avatar and nickname.",
        "导入失败" to "Import failed",
        "添加失败" to "Add failed",
        "保存失败" to "Save failed",
        "头像已保存" to "Avatar saved",
        "背景已保存" to "Background saved",
        "删除角色设定" to "Delete roleplay profile",
        "会删除此设定下的资源、好感度和所有沉浸对话数据。" to "This deletes this profile's assets, affection value, and all immersive chat data.",
        "沉浸扮演模式" to "Immersive roleplay",
        "开启后，对话页切换为聊天气泡样式，并使用当前角色设定作为系统提示词。" to "When enabled, chats use bubble style and the current character profile as the system prompt.",
        "导入角色设定" to "Import character profile",
        "请上传 zip 压缩包，包内放入 AI 需要扮演的角色详情 md/txt 文件，例如姓名、外貌、爱好、说话方式、关系设定、所处世界观等。可导入多个设定并切换。" to "Upload a zip containing md/txt character details such as name, appearance, hobbies, speaking style, relationship setup, and world setting. You can import and switch between multiple profiles.",
        "导入设定 zip" to "Import profile zip",
        "当前设定" to "Current profile",
        "角色表现" to "Character presentation",
        "头像" to "Avatar",
        "背景" to "Background",
        "AI 昵称" to "AI nickname",
        "上传头像" to "Upload avatar",
        "上传背景" to "Upload background",
        "清除所有对话数据并重置好感度" to "Clear all chats and reset affection",
        "表情包" to "Stickers",
        "设置短代码，例如 [sti_happy]。AI 回复中包含短代码时，软件会替换为对应表情图片。" to "Set short codes such as [sti_happy]. When the AI reply contains the code, Lyra replaces it with the matching sticker image.",
        "短代码" to "Short code",
        "上传表情包" to "Upload sticker",
        "未上传" to "Not uploaded",
        "当前" to "Current",
        "删除" to "Delete",
        "未命名平台" to "Unnamed provider",
        "模型服务已保存" to "Model service saved",
        "删除模型服务配置" to "Delete model service",
        "该操作会删除服务商、API Key、基础 URL 和预保存模型配置。" to "This deletes the provider, API key, base URL, and saved model list.",
        "模型服务" to "Model service",
        "搜索模型服务" to "Search model services",
        "新平台" to "New provider",
        "添加模型服务" to "Add model service",
        "没有匹配的模型服务" to "No matching model services",
        "至少保留一个模型服务" to "Keep at least one model service",
        "新模型服务" to "New model service",
        "返回列表" to "Back to list",
        "接口格式" to "API format",
        "服务商名称" to "Provider name",
        "基础 URL" to "Base URL",
        "请求路径" to "Request path",
        "用于兼容非默认 OpenAI 路径的服务商。留空时使用当前接口格式的默认请求路径。" to "Use this for providers with non-default OpenAI-compatible paths. Leave blank to use the default request path for the selected API format.",
        "安全提示：当前基础 URL 使用 HTTP 明文传输，API Key 和对话内容可能被同一网络中的第三方截获。" to "Security warning: this base URL uses plain HTTP. API keys and chat content may be intercepted on the same network.",
        "默认模型" to "Default model",
        "预保存模型，每行一个" to "Saved models, one per line",
        "保存" to "Save",
        "正在获取模型..." to "Fetching models...",
        "未获取到可用模型" to "No available models found",
        "获取模型失败" to "Failed to fetch models",
        "获取并替换模型" to "Fetch and replace models",
        "检测可达性" to "Check reachability",
        "正在检测模型可达性..." to "Checking model reachability...",
        "模型可达性检测完成" to "Model reachability check complete",
        "模型可达性检测失败" to "Model reachability check failed",
        "可达性检测结果" to "Reachability results",
        "选择要检测的模型" to "Select models to check",
        "选择模型检测可达性" to "Select models and check reachability",
        "可达性检测" to "Reachability check",
        "返回模型服务" to "Back to model service",
        "开始检测" to "Start check",
        "已选择" to "Selected",
        "没有可检测的模型" to "No models to check",
        "全选" to "Select all",
        "清空选择" to "Clear selection",
        "请先选择要检测的模型" to "Select at least one model to check",
        "检测中..." to "Checking...",
        "等待检测" to "Waiting to check",
        "服务商检测中..." to "Checking provider...",
        "服务商可用" to "Provider available",
        "服务商不可用" to "Provider unavailable",
        "无延迟数据" to "No latency data",
        "输出速度 " to "Output speed ",
        "可用" to "Available",
        "网络不可达或连接超时" to "Network unreachable or connection timed out",
        "检测失败" to "Check failed",
        "请求失败" to "Request failed",
        "删除平台" to "Delete provider",
        "当前目录" to "Current folder",
        "Termux 路径" to "Termux path",
        "仅 primary" to "primary only",
        "右上角加号选择目录后会立即刷新对话页顶部的小字目录名。" to "After choosing a folder from the top-right plus button, the folder name in the chat header updates immediately.",
        "聊天背景已保存" to "Chat background saved",
        "Material You 动态配色" to "Material You dynamic colors",
        "主题模式" to "Theme mode",
        "文本语言" to "Text language",
        "字体大小" to "Font size",
        "刷新率" to "Refresh rate",
        "聊天背景" to "Chat background",
        "已设置自定义背景" to "Custom background set",
        "纯色背景" to "Solid color background",
        "聊天背景预览" to "Chat background preview",
        "越低越接近纯色背景，越高背景图越清晰。" to "Lower values look closer to a solid color; higher values make the background image clearer.",
        "移除聊天背景" to "Remove chat background",
        "恢复纯色背景" to "Restore solid background",
        "已恢复纯色背景" to "Solid background restored",
        "启用" to "Enabled",
        "禁用" to "Disabled",
        "网站黑名单" to "Website blacklist",
        "AI 联网搜索和网页读取会跳过这些域名。普通域名精确匹配，* 通配符匹配子域名。" to "AI web search and page reading will skip these domains. Plain domains match exactly; * wildcards match subdomains.",
        "每行一个域名或 URL" to "One domain or URL per line",
        "保存后会自动归一化：移除协议、路径和尾部斜杠，但保留 www.。例如 x.com 只匹配 x.com；*.x.com 匹配 www.x.com、news.x.com 等子域名；如需同时拦截根域名和全部子域名，请同时填写 x.com 与 *.x.com。" to "Entries are normalized on save: protocol, path, and trailing slash are removed, while www. is preserved. For example, x.com only matches x.com; *.x.com matches www.x.com, news.x.com, and other subdomains. To block both the root domain and all subdomains, add both x.com and *.x.com.",
        "清空" to "Clear",
        "选择跟随系统、浅色或深色模式。返回主题设置后，其他外观选项会保持当前位置。" to "Choose system, light, or dark mode. Returning to Theme keeps the other appearance settings in place.",
        "跟随系统" to "Follow system",
        "浅色" to "Light",
        "深色" to "Dark",
        "默认跟随系统语言；当前未提供对应翻译或系统语言无法识别时，会使用默认简体中文。" to "Follows the system language by default. If no matching translation exists or the system language cannot be detected, Simplified Chinese is used.",
        "优先使用设备语言" to "Use device language first",
        "简体中文" to "Simplified Chinese",
        "默认语言" to "Default language",
        "跟随系统会交给设备自行在省电和流畅之间切换；固定刷新率会向系统请求指定帧率，实际是否生效取决于屏幕和系统策略。" to "Follow system lets the device balance power saving and smoothness. Fixed rates request a specific frame rate; whether it applies depends on the screen and system policy.",
        "跟随系统智能刷新率" to "Follow system adaptive refresh rate",
        "已选择" to "Selected",
        "预览文字大小" to "Preview text size",
        "你可以拖动滑块来调整字体大小。" to "Drag the slider to adjust font size.",
        "如果在使用过程中存在问题或建议，可在关于软件页面查看仓库链接并反馈。" to "If you have problems or suggestions, check repository links on the About page and send feedback.",
        "最小" to "Minimum",
        "较小" to "Smaller",
        "标准" to "Standard",
        "较大" to "Larger",
        "最大" to "Maximum",
        "回到底部" to "Back to bottom",
        "完成" to "Done",
        "添加附件" to "Add attachment",
        "输入消息" to "Message",
        "停止" to "Stop",
        "发送" to "Send",
        "本轮强制使用" to "Forced this request",
        "点击移除 Skill" to "Remove Skill",
        "选择技能" to "Choose Skill",
        "输入 / 选择本轮要强制使用的 Skill" to "Type / to choose Skills for this request",
        "没有匹配的 Skill" to "No matching Skills",
        "逐字显示" to "Typewriter",
        "渐变显示" to "Fade in",
        "好感度" to "Affection",
        "添加" to "Add",
        "你" to "You",
        "移除" to "Remove",
        "视频" to "Video",
        "音频" to "Audio",
        "过程记录已展开" to "Process log expanded",
        "过程记录已收起" to "Process log collapsed",
        "任务处理中" to "Processing",
        "任务耗时" to "Elapsed",
        "确认工具调用" to "Confirm tool call",
        "拒绝时给 AI 的修改要求" to "Instructions for the AI if rejected",
        "无审批" to "No approval",
        "仅当前会话生效，开启前需要确认风险" to "Current chat only; confirmation required before enabling",
        "已开启：需要审批的操作将自动同意" to "Enabled: approval requests will be accepted automatically",
        "开启无审批" to "Enable no approval",
        "开启后，AI 执行需要用户审批的操作时将自动同意。可能导致文件被修改、命令被执行或远程服务被调用，请只在信任当前任务时开启。该设置仅对当前会话生效。" to "After enabling this, AI actions that normally require your approval will be approved automatically. This may modify files, run commands, or call remote services. Enable it only when you trust the current task. This setting only applies to the current chat.",
        "确认开启" to "Enable",
        "本会话无需确认" to "No confirmation for this chat",
        "同意" to "Allow",
        "不同意" to "Deny",
        "收纳" to "Collapse",
        "展开" to "Expand",
        "文件变更" to "File changes",
        "收起变更详情" to "Collapse diff details",
        "点击审视变更前后代码" to "Tap to review before/after code",
        "平台" to "Provider",
        "模型" to "Model",
        "编辑并重新生成" to "Edit and regenerate",
        "重新生成" to "Regenerate",
        "取消" to "Cancel",
        "工具结果" to "Tool result",
        "思考详情已展开" to "Thinking details expanded",
        "thinking..." to "thinking...",
        "思考完毕" to "Thinking complete",
        "复制" to "Copy",
        "正在组织输出..." to "Composing response...",
        "选择文本" to "Select text",
        "修改并重新生成" to "Edit and regenerate",
        "收起" to "Collapse",
        "继续对话" to "Continue chat",
        "空结果" to "Empty result",
        "调用工具" to "Tool call",
        "查看详情" to "View details",
        "工具调用" to "Tool call",
        "工具调用详情" to "Tool call details",
        "未知工具" to "Unknown tool",
        "工具输入" to "Tool input",
        "调用结果" to "Result",
        "使用工具中... / 工具结果已收起" to "Using tool... / tool result collapsed",
        "审视变更" to "Review diff",
        "差异" to "Diff",
        "(无行级差异)" to "(No line-level diff)",
        "变更前" to "Before",
        "变更后" to "After",
        "(空)" to "(Empty)",
        "任务通知" to "Task notifications",
        "任务完成通知" to "Task completion notifications",
        "下载和定时任务完成或失败后推送系统通知" to "Send system notifications when downloads or scheduled tasks complete or fail",
        "定时任务" to "Scheduled tasks",
        "添加定时任务" to "Add scheduled task",
        "暂无定时任务" to "No scheduled tasks",
        "可在这里手动添加，或在对话中用自然语言让 AI 创建。系统会通过 WorkManager 延期唤醒执行，受省电策略影响时不保证秒级准时。" to "Add tasks manually here, or ask the AI to create one in chat. WorkManager wakes the app for execution, but battery policies may prevent second-level precision.",
        "下载任务" to "Download tasks",
        "清除已完成下载" to "Clear finished downloads",
        "暂无下载任务" to "No download tasks",
        "AI 使用下载文件工具后，可在这里查看进度、速度和结果。" to "When the AI uses the download tool, progress, speed, and results appear here.",
        "删除定时任务" to "Delete scheduled task",
        "编辑" to "Edit",
        "未知错误" to "Unknown error",
        "正在执行" to "Running",
        "已完成" to "Completed",
        "点击查看完整结果" to "Tap to view full result",
        "状态" to "Status",
        "频率" to "Schedule",
        "最近执行" to "Last run",
        "尚未执行" to "Not run yet",
        "输出结果" to "Output",
        "错误信息" to "Error",
        "关闭" to "Close",
        "编辑定时任务" to "Edit scheduled task",
        "任务名称" to "Task name",
        "任务说明" to "Task description",
        "执行频率" to "Frequency",
        "执行时间" to "Run time",
        "格式" to "Format",
        "星期（1=周一，7=周日）" to "Weekday (1=Mon, 7=Sun)",
        "每月日期（1-31）" to "Day of month (1-31)",
        "服务商" to "Provider",
        "执行模型" to "Execution model",
        "从预保存模型选择" to "Choose from saved models",
        "任务说明不能为空" to "Task description cannot be empty",
        "执行时间格式不正确" to "Invalid run time format",
        "一次性任务时间必须晚于当前时间" to "One-time task must be scheduled in the future",
        "星期必须为 1 到 7" to "Weekday must be 1 to 7",
        "每月日期必须为 1 到 31" to "Day of month must be 1 to 31",
        "等待下载" to "Waiting to download",
        "失败" to "Failed",
        "一次性" to "Once",
        "每天" to "Daily",
        "每周" to "Weekly",
        "每月" to "Monthly",
        "等待执行" to "Waiting",
        "未知大小" to "Unknown size",
        "媒体文件" to "Media file",
        "正在保存..." to "Saving...",
        "保存到下载" to "Save to Downloads",
        "加载媒体..." to "Loading media...",
        "图片加载失败，可复制链接到浏览器打开。" to "Image failed to load. Copy the link and open it in a browser.",
        "图片预览" to "Image preview",
        "无法识别媒体地址" to "Unrecognized media URL",
        "全屏" to "Fullscreen",
        "视频预览" to "Video preview",
        "图片解码失败" to "Image decode failed",
        "全屏播放" to "Play fullscreen",
        "播放" to "Play",
        "媒体预览" to "Media preview",
        "保存文件" to "Save file",
        "无法预览此媒体" to "Cannot preview this media",
        "关闭预览" to "Close preview",
        "无法打开媒体" to "Unable to open media",
        "复制代码" to "Copy code",
        "Base64 文件" to "Base64 file",
        "无法解析 data URL。" to "Unable to parse data URL.",
        "复制原始值" to "Copy raw value",
        "无法创建下载文件" to "Unable to create download file",
        "无法写入下载文件" to "Unable to write download file",
        // Resource-backed translations kept in sync with values-en/strings.xml.
        "子代理编排" to "Sub-agent orchestration",
        "复杂任务允许主模型分派独立子代理" to "Allow the main model to delegate complex work",
        "请先在设置中添加并启用子代理模型" to "Add and enable a sub-agent model in Settings first",
        "选择子代理模型并描述各自擅长的任务" to "Choose sub-agent models and describe their strengths",
        "开启后，主模型可在复杂任务中调用 run_sub_agents，将独立子任务交给已启用的子代理模型执行。子代理对话不进入普通历史，只把最终结果返回主模型。" to "When enabled, the main model can call run_sub_agents for complex tasks and delegate independent work to enabled sub-agent models. Sub-agent chats stay out of normal history and return only final results.",
        "子代理模型" to "Sub-agent model",
        "擅长代码审查、Bug 检查、资料核验或独立方案分析。" to "Good at code review, bug checks, source verification, or independent solution analysis.",
        "暂无子代理模型。请从已添加的模型服务中选择模型，并填写它擅长的任务说明。" to "No sub-agent models yet. Choose a model from existing model services and describe what it is good at.",
        "子代理已删除" to "Sub-agent deleted",
        "子代理已保存" to "Sub-agent saved",
        "编辑子代理模型" to "Edit sub-agent model",
        "删除子代理模型" to "Delete sub-agent model",
        "确定删除“%1\$s”吗？该操作不会删除原模型服务。" to "Delete \"%1\$s\"? This will not delete the original model service.",
        "正在执行子代理任务" to "Running sub-agent task",
        "子代理任务完成" to "Sub-agent tasks complete",
        "子代理名称" to "Sub-agent name",
        "能力说明" to "Capability description",
        "AI 对话" to "Chat",
        "日志" to "Logs",
        "统计" to "Statistics",
        "任务" to "Tasks",
        "设置" to "Settings",
        "你已在新对话中，无需重复操作" to "You are already in a new chat.",
        "无法打开安装器" to "Unable to open installer",
        "授权未完成，可稍后在关于软件中继续安装" to "Permission is not granted yet. You can install later from About.",
        "请授权安装未知来源应用，返回后将继续安装" to "Allow installing unknown apps. Installation will continue after you return.",
        "已导入 %1\$s" to "Imported %1\$s",
        "正在导入备份…" to "Importing backup...",
        "导入完成：%1\$s" to "Import complete: %1\$s",
        "导入失败：%1\$s" to "Import failed: %1\$s",
        "下载完成，准备安装" to "Download complete. Preparing installation.",
        "下载失败" to "Download failed",
        "准备下载" to "Preparing download",
        "正在下载 Skills 仓库…" to "Downloading Skills repository...",
        "功能" to "Functions",
        "历史会话" to "Chat History",
        "搜索历史对话" to "Search chats",
        "已选择 %1\$d" to "%1\$d selected",
        "置顶" to "Pin",
        "取消选择" to "Cancel selection",
        "暂无会话" to "No chats yet",
        "置顶" to "Pinned",
        "今天" to "Today",
        "昨天" to "Yesterday",
        "一周内" to "Within a week",
        "一月内" to "Within a month",
        "个人资料" to "Profile",
        "昵称" to "Nickname",
        "选择头像图片" to "Choose avatar",
        "裁剪缩放" to "Crop zoom",
        "水平位置" to "Horizontal position",
        "垂直位置" to "Vertical position",
        "%1\$d 个文件 · %2\$s" to "%1\$d files · %2\$s",
        "已启用" to "Enabled",
        "已禁用" to "Disabled",
        "删除 Skill" to "Delete Skill",
        "该操作会删除此 Skill 包及其本地文件。" to "This will delete the Skill package and its local files.",
        "Skills 能力包" to "Skills",
        "支持从文件、仓库链接或手动编辑 SKILL.md 导入。AI 会先查看 name/description 判断是否需要，再按需读取包内文件。" to "Import from files, repositories, or manual SKILL.md editing. The AI checks name/description first and reads package files only when needed.",
        "导入 Skills" to "Import Skills",
        "%1\$d 个已安装" to "%1\$d installed",
        "暂无 Skills" to "No Skills yet",
        "导入 zip、单个 SKILL.md 或仓库后会在这里显示，可启用、禁用或删除。" to "Imported zip files, single SKILL.md files, or repositories will appear here.",
        "已安装" to "Installed",
        "从文件导入" to "Import from file",
        "选择 zip 或单个 SKILL.md" to "Choose a zip or SKILL.md",
        "从仓库导入" to "Import from repository",
        "手动添加" to "Add manually",
        "直接编辑 SKILL.md" to "Edit SKILL.md directly",
        "从仓库导入" to "Import from repository",
        "输入 GitHub、Gitee 或 GitLab 仓库链接，Lyra Code 会自动下载仓库文件并识别 SKILL.md。" to "Enter a GitHub, Gitee, or GitLab repository URL. Lyra Code will download the repository and find SKILL.md.",
        "GitHub / Gitee / GitLab 链接" to "GitHub / Gitee / GitLab URL",
        "导入" to "Import",
        "手动添加" to "Add manually",
        "直接编辑 SKILL.md 内容，保存后会作为一个独立 Skill 安装。" to "Edit SKILL.md directly and save it as a standalone Skill.",
        "保存 Skill" to "Save Skill",
        "%1\$d 个文件 · %2\$s" to "%1\$d files · %2\$s",
        "撤销" to "Undo",
        "重做" to "Redo",
        "无法预览图片" to "Unable to preview image",
        "原图上传" to "Upload original",
        "裁剪" to "Crop",
        "画笔" to "Brush",
        "马赛克" to "Mosaic",
        "旋转" to "Rotate",
        "还原" to "Reset",
        "粗细" to "Thickness",
        "已置顶" to "Pinned",
        "会话操作" to "Chat actions",
        "对话标题" to "Chat title",
        "保存标题" to "Save title",
        "取消置顶" to "Unpin",
        "置顶对话" to "Pin chat",
        "进入多选" to "Multi-select",
        "删除对话" to "Delete chat",
        "新聊天" to "New chat",
        "已获取 %1\$d 个模型" to "Fetched %1\$d models",
        "好感度 %1\$d" to "Affection %1\$d",
        "选择服务商" to "Choose provider",
        "搜索服务商" to "Search providers",
        "选择模型" to "Choose model",
        "搜索模型" to "Search models",
        "切换提示词" to "Switch prompt",
        "搜索提示词" to "Search prompts",
        "推理深度" to "Reasoning depth",
        "并非所有模型都支持深度调整；不支持时会自动保持服务商原始参数，避免请求失败。" to "Not every model supports depth control. Unsupported providers will keep their original request parameters.",
        "相册" to "Album",
        "相机" to "Camera",
        "文件" to "File",
        "新建沉浸对话" to "New immersive chat",
        "保留当前角色记忆和好感度" to "Keep current character memory and affection",
        "未配置" to "Not configured",
        "未选择" to "Not selected",
        "获取当前平台模型" to "Fetch current provider models",
        "从 models 端点刷新可用模型" to "Refresh available models from the models endpoint",
        "提示词" to "Prompt",
        "默认助手" to "Default assistant",
        "推理深度" to "Reasoning depth",
        "低" to "Low",
        "中" to "Medium",
        "高" to "High",
        "超高" to "Ultra",
        "自动" to "Auto",
        "返回" to "Back",
        "过程记录已收起 · thinking %1\$d / 工具 %2\$d" to "Process log collapsed · thinking %1\$d / tools %2\$d",
        "任务处理中 · " to "Processing · ",
        "任务耗时 · " to "Duration · ",
        "文件变更 %1\$d" to "File changes %1\$d",
        "正在组织输出…" to "Composing...",
        "%1\$d小时%2\$d分%3\$d秒" to "%1\$dh %2\$dm %3\$ds",
        "%1\$d分%2\$d秒" to "%1\$dm %2\$ds",
        "%1\$d秒" to "%1\$ds",
        "未命名文件" to "Unnamed file",
        "… 已截断预览，完整工具结果共 %1\$d 字符。" to "... Preview truncated. Full tool result has %1\$d characters.",
        "工具调用详情已展开" to "Tool details expanded",
        "使用工具中… / 工具结果已收起" to "Using tool... / tool result collapsed",
        "工具返回 %1\$d 字符：%2\$s" to "Tool returned %1\$d characters: %2\$s",
        "收起变更" to "Collapse change",
        "（无行级差异）" to "(No line diff)",
        "（空）" to "(empty)",
        "文件" to "File",
        "%1\$s 文本" to "%1\$s text",
        "%1\$s 代码" to "%1\$s code",
        "%1\$s 压缩包" to "%1\$s archive",
        "PDF 文档" to "PDF document",
        "%1\$s 文档" to "%1\$s document",
        "%1\$s 文件" to "%1\$s file",
        "新对话" to "New chat",
        "沉浸对话" to "Immersive chat",
        "运行中" to "Running",
        "已中断" to "Interrupted",
        "继续运行" to "Continue",
        "读取上传文件" to "Reading upload",
        "已上传 %1\$s" to "Uploaded %1\$s",
        "处理拍照图片" to "Processing photo",
        "待发送 %1\$d 个附件" to "%1\$d attachments pending",
        "获取模型列表" to "Fetching models",
        "已批准工具调用" to "Tool call approved",
        "已拒绝工具调用" to "Tool call rejected",
        "等待确认：%1\$s" to "Waiting for confirmation: %1\$s",
        "TODO 列表已设置，共 %1\$d 项。" to "TODO list set, %1\$d items.",
        "未命名步骤" to "Untitled step",
        "新对话" to "New chat",
        "用户中断了当前任务。" to "The user interrupted the current task.",
        "审查日志" to "Audit Log",
        "暂无日志" to "No logs yet",
        "模型请求、工具审查和关键执行记录会显示在这里。" to "Model requests, tool reviews, and key execution records will appear here.",
        "日志详情" to "Log Detail",
        "系统" to "System",
        "厂商" to "Manufacturer",
        "品牌" to "Brand",
        "型号" to "Model",
        "设备代号" to "Codename",
        "Android 版本" to "Android version",
        "构建版本" to "Build",
        "安全补丁" to "Security patch",
        "不支持" to "Not supported",
        "硬件" to "Hardware",
        "CPU 核心数" to "CPU cores",
        "该设置项暂未开放。" to "This setting is not available yet.",
        "设置" to "Settings",
        "模型与服务" to "Models and Services",
        "个人资料" to "Profile",
        "昵称、头像与用户显示信息" to "Nickname, avatar, and display information",
        "配置 AI 服务商、API Key 与默认模型" to "Configure AI providers, API keys, and default models",
        "联网搜索" to "Web search",
        "配置网站黑名单，过滤垃圾或不可信来源" to "Configure domain blacklist and filter unreliable sources",
        "工作目录" to "Workspace",
        "当前：%1\$s" to "Current: %1\$s",
        "配置本地命令执行与路径映射" to "Configure local command execution and path mapping",
        "MCP 服务器" to "MCP servers",
        "配置远程 MCP 工具服务器" to "Configure remote MCP tool servers",
        "MCP 服务端" to "MCP server mode",
        "将本机工具提供给其他 MCP 客户端" to "Expose local tools to other MCP clients",
        "SSH 连接" to "SSH connections",
        "配置可由 AI 调用的远程服务器" to "Configure remote servers callable by AI",
        "配置云端文件与备份服务器" to "Configure cloud files and backup servers",
        "文件传输" to "File transfer",
        "配置 FTP/FTPS/SFTP 存储服务器" to "Configure FTP/FTPS/SFTP storage servers",
        "微型服务器" to "Mini server",
        "工作区 HTTP 静态站点调试" to "Debug workspace HTTP static sites",
        "个性化" to "Personalization",
        "主题设置" to "Theme",
        "当前：%1\$s · %2\$s · %3\$s" to "Current: %1\$s · %2\$s · %3\$s",
        "当前：%1\$s · %2\$s · %3\$s · %4\$s" to "Current: %1\$s · %2\$s · %3\$s · %4\$s",
        "系统提示词" to "System prompts",
        "配置不同用途的默认提示词" to "Configure default prompts for different uses",
        "当前：%1\$s，管理角色设定与表情包" to "Current: %1\$s, manage characters and stickers",
        "已开启" to "On",
        "已关闭" to "Off",
        "已安装 %1\$d 个能力包" to "%1\$d skill packages installed",
        "通用" to "General",
        "AI Agent 工具" to "AI Agent tools",
        "查看工具说明并启用或禁用" to "View tool descriptions and enable or disable tools",
        "缓存与存储" to "Cache and storage",
        "扫描占用空间并清理安全缓存" to "Scan storage usage and clear safe caches",
        "数据导出导入" to "Data export/import",
        "本地或 WebDAV 备份与恢复" to "Local or WebDAV backup and restore",
        "系统权限" to "System permissions",
        "配置 Root、Shizuku Shell 与 su 命令" to "Configure Root, Shizuku Shell, and su command",
        "应用权限" to "App permissions",
        "查看媒体、摄像头、位置与 Termux 权限" to "View media, camera, location, and Termux permissions",
        "开源许可证" to "Open source licenses",
        "查看第三方组件许可证" to "View third-party component licenses",
        "关于软件" to "About",
        "版本、包名和安全说明" to "Version, package name, and security notes",
        "个人资料" to "Profile",
        "联网搜索" to "Web search",
        "工作目录" to "Workspace",
        "主题设置" to "Theme",
        "应用权限" to "App permissions",
        "系统权限" to "System permissions",
        "AI Agent 工具" to "AI Agent tools",
        "缓存与存储" to "Cache and storage",
        "MCP 服务器" to "MCP servers",
        "MCP 服务端" to "MCP server mode",
        "SSH 连接" to "SSH connections",
        "文件传输" to "File transfer",
        "微型服务器" to "Mini server",
        "终端日志" to "Terminal logs",
        "数据导出导入" to "Data export/import",
        "系统提示词" to "System prompts",
        "开源许可证" to "Open source licenses",
        "关于软件" to "About",
        "手机信息" to "Device information",
        "设置" to "Settings",
        "媒体超过" to "Media exceeds"
    )

    fun isEnglish(): Boolean {
        return when (AppSettings.normalizeLanguageMode(languageMode)) {
            AppSettings.LANGUAGE_EN -> true
            AppSettings.LANGUAGE_ZH_CN -> false
            else -> Locale.getDefault().language.equals("en", ignoreCase = true)
        }
    }

    fun translate(text: String): String {
        if (!isEnglish()) return text
        translations[text]?.let { return it }
        val dynamic = translateDynamic(text)
        if (dynamic != text) return dynamic
        return translateBySegments(text)
    }

    private val segmentTranslations: List<Pair<String, String>> = listOf(
        "AI 联网搜索和网页读取会跳过这些域名。普通域名精确匹配，* 通配符匹配子域名。" to "AI web search and page reading skip these domains. Plain domains match exactly; * matches subdomains.",
        "补充模式会在现有数据上新增并去重，推荐使用。覆盖模式会替换已有兼容配置，存在数据丢失风险。" to "Supplement mode adds and deduplicates data on top of existing data. Overwrite mode replaces compatible existing data and may cause data loss.",
        "可单独选择导出范围；跨版本导入时会跳过不兼容结构并导入可兼容部分。" to "You can choose what to export. Incompatible structures are skipped during cross-version import.",
        "包含密钥的备份可直接导入使用，但必须妥善保管，不要分享给他人。" to "Backups containing keys can be imported directly, but must be stored carefully and never shared.",
        "面向 Android 的本地 AI Agent 工具，支持多平台模型、流式对话、Termux、工作区文件操作、联网搜索、MCP、Skills、TODO 进度和文件变更审查。" to "A local AI Agent tool for Android with multi-provider models, streaming chat, Termux, workspace file tools, web search, MCP, Skills, TODO progress, and file change review.",
        "总占用按 Android 设置页常见口径估算" to "Total usage is estimated using the common Android Settings method",
        "清理范围仅包含临时上传、图片裁剪、拍照预览和 AI 响应磁盘缓存" to "Cleanup only includes temporary uploads, image crops, camera previews, and AI response disk cache",
        "不会删除历史对话、模型配置、API Key、MCP/SSH、Skills、头像或工作目录文件" to "It will not delete chat history, model configs, API keys, MCP/SSH, Skills, avatars, or workspace files",
        "首次使用前，请在 Termux 中开启外部应用调用权限。" to "Before first use, enable external app calls in Termux.",
        "Termux:API 可选；未安装 Termux:API 时，Lyra Code 会使用 RunCommandService 后台静默执行命令。" to "Termux:API is optional. Without it, Lyra Code uses RunCommandService to run commands silently in the background.",
        "run_command 会直接回传 exit_code、stdout、stderr；只有输出过大或超时时，再重定向到工作目录文件。" to "run_command returns exit_code, stdout, and stderr directly. It redirects to a workspace file only when output is too large or times out.",
        "AI 使用 SSH 执行命令会像文件修改一样请求确认。" to "AI SSH commands request confirmation like file modifications.",
        "安装软件或修改服务器前，AI 应先检查系统、CPU/GPU、内存、磁盘和权限。" to "Before installing software or changing a server, the AI should check system, CPU/GPU, memory, disk, and permissions.",
        "复杂交互式 shell（如 vim/top/交互 ssh）不适合由内置 SSH 工具执行。" to "Complex interactive shells such as vim, top, or interactive ssh are not suitable for the built-in SSH tool.",
        "请添加远程或局域网 MCP Server URL。" to "Add a remote or LAN MCP Server URL.",
        "若服务器使用 HTTP 明文连接，API Key 和工具参数可能被同一网络中的第三方截获。" to "If the server uses plain HTTP, API keys and tool parameters may be intercepted on the same network.",
        "支持 Streamable HTTP 与 SSE。" to "Supports Streamable HTTP and SSE.",
        "Android 端不直接启动 stdio MCP Server。" to "Android does not start stdio MCP Servers directly.",
        "将 Lyra Code 已启用的 Agent 工具和已启用 MCP 工具暴露给其他 MCP Client。" to "Expose enabled Lyra Code Agent tools and enabled MCP tools to other MCP clients.",
        "其他 MCP Client 可通过 http://主机:端口/mcp 连接。" to "Other MCP clients can connect through http://host:port/mcp.",
        "若监听局域网或公网，建议设置认证 Key。" to "Set an auth key when listening on LAN or public networks.",
        "添加后，AI 可在用户确认后把 WebDAV 文件下载到工作区，或把工作区文件上传到 WebDAV。" to "After adding, the AI can download WebDAV files to the workspace or upload workspace files to WebDAV after confirmation.",
        "添加 FTP、FTPS 或 SFTP 后，AI 可列出远程目录、搜索文件，并在用户确认后下载到工作区或从工作区上传。" to "After adding FTP, FTPS, or SFTP, the AI can list remote directories, search files, and download/upload after confirmation.",
        "FTP 是明文协议，建议只在可信局域网使用；公网或敏感文件请优先使用 SFTP/FTPS。" to "FTP is plain text. Use it only on trusted LANs; prefer SFTP/FTPS for public networks or sensitive files.",
        "FTP/FTPS 推荐开启被动模式，兼容 NAT 和多数服务器。" to "Passive mode is recommended for FTP/FTPS and works better with NAT and most servers.",
        "通过 Magisk、KernelSU 等 su 管理器授权。" to "Authorize through su managers such as Magisk or KernelSU.",
        "不可用时可回退到已授权的 Shell。" to "Falls back to authorized Shell when unavailable.",
        "通过 Shizuku 以 Android shell 身份执行系统命令，每次执行前都需要用户确认。" to "Run system commands as Android shell through Shizuku. Each run requires confirmation.",
        "通过自定义 su 命令执行 Root 命令，每次执行前都需要用户确认；不可用时可按设置回退到 Shell。" to "Run Root commands through a custom su command. Each run requires confirmation; it may fall back to Shell based on settings.",
        "Root 和 Shell 开关都关闭时，AI 不会看到任何系统命令工具。" to "When both Root and Shell are off, the AI cannot see any system command tools.",
        "所有 Shell/Root 命令都会先显示完整命令并请求确认；Root 命令风险更高。" to "All Shell/Root commands show the full command and request confirmation first. Root commands are higher risk.",
        "普通 ADB 不会永久赋予应用 shell 身份，本应用通过 Shizuku 获取该能力。" to "Regular ADB does not permanently grant shell identity to apps; Lyra uses Shizuku for that capability.",
        "用于截图反馈、排查兼容性问题，以及让硬件检查 Agent 分析当前设备环境。" to "Used for screenshots, compatibility diagnosis, and hardware analysis by the Hardware Check Agent.",
        "部分项目受系统权限和 Android 沙箱限制，可能只能显示近似信息。" to "Some fields may only be approximate due to system permissions and Android sandboxing.",
        "API Key 保存在本机配置中；对话、工具输出、缓存和审查日志默认留在本机。" to "API keys are stored in local config. Chats, tool outputs, caches, and review logs stay local by default.",
        "使用第三方模型接口、HTTP 明文 URL、联网搜索、MCP 或 Termux 命令时，数据会按用户配置发送到对应服务或本机执行环境。" to "When using third-party model APIs, plain HTTP URLs, web search, MCP, or Termux commands, data is sent according to the user's configuration.",
        "选择不同用途的系统提示词。修改后会保存到当前预设；恢复预设只影响当前选中的提示词。" to "Choose system prompts for different use cases. Edits are saved to the current preset; restore only affects the selected prompt.",
        "通过用户确认后添加、修改、启用、禁用或删除 MCP、SSH、WebDAV、Skills 与其他 Agent 工具配置。" to "Add, edit, enable, disable, or delete MCP, SSH, WebDAV, Skills, and other Agent tool configs after user confirmation.",
        "跨普通会话按关键词和时间段搜索历史记录，不读取思维链或工具日志。" to "Search normal chat history by keyword and time range without reading thinking chains or tool logs.",
        "新会话首次对话时，根据用户第一条消息设置简短主题标题。" to "For the first message in a new chat, generate a short topic title.",
        "声明网页引用来源，并要求最终回答就近标注来源链接。" to "Declare web sources and ask the final answer to cite nearby source links.",
        "使用内嵌 WebView 搜索互联网。" to "Search the web using the embedded WebView.",
        "使用应用原生 HTTP/HTTPS 客户端下载到工作区或共享存储，支持请求头和 SHA-256 校验。" to "Download to the workspace or shared storage using the native HTTP/HTTPS client, with headers and SHA-256 verification.",
        "列出或管理一次性、每日、每周和每月后台 AI 任务。" to "List or manage one-time, daily, weekly, and monthly background AI tasks.",
        "沉浸扮演模式下调整好感度并触发表情短代码。" to "Adjust affection and trigger sticker short codes in immersive roleplay mode.",
        "展示 Agent 当前任务计划。" to "Show the Agent's current task plan.",
        "读取指定历史会话的用户消息和 AI 最终回复，用于总结与趋势分析。" to "Read user messages and final AI replies from selected chats for summaries and trend analysis.",
        "读取设备系统、CPU、内存、存储、分辨率、网络、蓝牙、电池等诊断信息。" to "Read device diagnostics such as system, CPU, memory, storage, resolution, network, Bluetooth, and battery.",
        "读取用户应用和系统应用的名称、包名、版本、大小及签名证书 SHA-256。" to "Read user/system app name, package, version, size, and signing certificate SHA-256.",
        "读取微型服务器连接、资源加载和页面错误日志，便于自动化调试。" to "Read mini server connection, resource loading, and page error logs for automated debugging.",
        "以当前工作目录作为静态站点根目录，适合调试 Vue/Vite 文档站或普通 HTML/CSS/JS。" to "Use the current workspace as the static site root, suitable for Vue/Vite docs or regular HTML/CSS/JS debugging.",
        "127.0.0.1 仅本机访问；0.0.0.0 可被局域网、内网穿透或公网映射访问。" to "127.0.0.1 is local only; 0.0.0.0 can be reached from LAN, tunnels, or public mappings.",
        "安全提示：面向局域网或公网映射时建议设置用户名和密码；HTTP 明文会暴露访问内容和账号密码。" to "Security: set a username and password for LAN or public mappings. Plain HTTP exposes content and credentials.",
        "HTTPS 使用内置自签名证书，浏览器会提示不受信任；公网或正式分享建议使用内网穿透/反向代理提供可信 TLS。" to "HTTPS uses a built-in self-signed certificate and browsers will warn. For public sharing, use a tunnel or reverse proxy with trusted TLS.",
        "HTTP 访问会返回 308 跳转到 HTTPS；适合反向代理或同端口 HTTPS 调试。" to "HTTP returns a 308 redirect to HTTPS; useful for reverse proxies or same-port HTTPS debugging.",
        "没有 index.html 时显示目录文件；公网环境不建议开启。" to "Show directory files when index.html is missing. Not recommended for public networks.",
        "适合 Vue Router / VitePress / 单页应用刷新路径。" to "Suitable for Vue Router, VitePress, and single-page app refresh paths.",
        "在局域网内尝试发布 _http._tcp 服务，便于支持 mDNS 的设备发现。" to "Publish an _http._tcp service on LAN for devices that support mDNS discovery.",
        "绑定域名，每行一个" to "Bound domains, one per line",
        "证书链 PEM，可粘贴" to "Certificate chain PEM, pasteable",
        "私钥 PEM，可粘贴" to "Private key PEM, pasteable",
        "证书库/私钥密码，可空" to "Keystore/private key password, optional",
        "未配置自定义证书时会使用内置自签名证书。证书库支持 PKCS12/JKS；PEM 私钥需为未加密 PKCS#8 格式。" to "If no custom certificate is configured, the built-in self-signed certificate is used. Keystores support PKCS12/JKS; PEM private keys must be unencrypted PKCS#8.",
        "安全提示：HTTP 明文连接可能泄露认证 key、工具参数和返回内容。" to "Security: plain HTTP may leak auth keys, tool parameters, and returned content.",
        "安全提示：HTTP 明文连接可能泄露账号、密码和文件内容。" to "Security: plain HTTP may leak account, password, and file content.",
        "安全提示：FTP 明文连接可能泄露账号、密码和文件内容。" to "Security: plain FTP may leak account, password, and file content.",
        "使用 AUTH TLS 升级连接；关闭后尝试隐式 FTPS。" to "Use AUTH TLS to upgrade the connection; when off, implicit FTPS is attempted.",
        "仅用于自签名证书服务器；不建议在公网服务开启。" to "Only for self-signed certificate servers; not recommended for public services.",
        "开启后使用私钥和可选口令登录 SFTP。" to "Use a private key and optional passphrase for SFTP login.",
        "保存此偏好，后续大文件传输可按此策略扩展。" to "Save this preference so future large transfers can use this strategy.",
        "仅部分 SFTP 服务器支持。" to "Only some SFTP servers support this.",
        "导出 Lyra Code 数据到本地或 WebDAV，执行前需要用户确认。" to "Export Lyra Code data locally or to WebDAV after confirmation.",
        "从本地或 WebDAV 用补充模式导入备份，执行前需要用户确认。" to "Import backups from local storage or WebDAV in supplement mode after confirmation.",
        "加入 Lyra Code QQ 群聊" to "Join the Lyra Code QQ group",
        "加入 Lyra Code Discord 社区" to "Join the Lyra Code Discord community",
        "关于页面仓库与社交群聊 SVG 图标。" to "Repository and social SVG icons on the About page.",
        "本地 LaTeX 数学公式渲染。源码随工程 third_party/jlatexmath 保留。" to "Local LaTeX math rendering. Source is kept under third_party/jlatexmath.",
        "数学公式渲染字体。完整字体许可随 third_party/jlatexmath/assets 分发。" to "Math rendering fonts. Full font licenses are distributed under third_party/jlatexmath/assets.",
        "Lyra Code 使用以下开源组件。点击条目可查看内置的原始许可证文本。" to "Lyra Code uses the following open-source components. Tap an item to view the bundled original license text.",
        "Markdown GFM AST 解析，支持表格、列表和数学节点。" to "Markdown GFM AST parsing with tables, lists, and math nodes.",
        "Material Design 3 组件。" to "Material Design 3 components.",
        "声明式 UI 框架。" to "Declarative UI framework.",
        "主要开发语言与编译器。" to "Main development language and compiler.",
        "Android 构建工具链。" to "Android build toolchain.",
        "Compose Activity 集成。" to "Compose Activity integration.",
        "Android Kotlin 扩展与兼容层。" to "Android Kotlin extensions and compatibility layer.",
        "JSON 解析与序列化。" to "JSON parsing and serialization.",
        "HTTP、SSE 兼容读取与 MCP Streamable HTTP 通信。" to "HTTP, SSE-compatible reading, and MCP Streamable HTTP communication.",
        "单元测试框架，仅测试构建使用。" to "Unit test framework, used only for test builds.",
        "异步任务与流式请求。" to "Async tasks and streaming requests.",
        "SAF 工作区文件访问。" to "SAF workspace file access.",
        "本地敏感配置加密存储。" to "Local encrypted storage for sensitive configuration.",
        "界面图标库。" to "UI icon library.",
        "应用内更新会下载 APK 二进制文件并校验 SHA-256。安装前 Android 会要求用户允许 Lyra Code 安装未知来源应用。" to "In-app update downloads the APK binary and verifies SHA-256. Android will ask you to allow Lyra Code to install unknown apps before installation.",
        "关闭进入软件时每日一次的新版本弹窗，不影响手动检测更新。" to "Disable the once-per-day update popup on app launch. Manual update checks still work.",
        "这是重要更新，建议尽快安装。" to "This is an important update. Install it soon.",
        "当前已是最新版本" to "You are on the latest version.",
        "检查更新失败" to "Update check failed",
        "发现新版本，点击查看" to "New version available. Tap to view.",
        "正在检查更新" to "Checking for updates",
        "正在启动" to "Starting",
        "正在清理缓存" to "Cleaning cache",
        "缓存已清理" to "Cache cleared",
        "扫描完成" to "Scan complete",
        "清理全部缓存" to "Clear all cache",
        "可安全清理缓存" to "Safely cleanable cache",
        "裁剪图片临时文件" to "Temporary cropped images",
        "拍照上传临时文件" to "Temporary camera uploads",
        "AI 响应缓存" to "AI response cache",
        "代码缓存" to "Code cache",
        "系统缓存" to "System cache",
        "系统临时缓存" to "System temporary cache",
        "应用安装包" to "Application package",
        "应用持久数据" to "Persistent app data",
        "应用数据" to "App data",
        "应用总占用" to "Total app usage",
        "存储占用" to "Storage usage",
        "构建信息" to "Build information",
        "手机信息" to "Device information",
        "版本与更新" to "Version and updates",
        "隐私与安全" to "Privacy and security",
        "官网" to "Official website",
        "社交群聊" to "Social groups",
        "仓库" to "Repositories",
        "开源许可证" to "Open-source licenses",
        "个人资料" to "Profile",
        "系统提示词" to "System prompts",
        "提示词配置" to "Prompt configurations",
        "模型服务配置" to "Model provider configuration",
        "MCP 服务器配置" to "MCP server configuration",
        "SSH 连接配置" to "SSH connection configuration",
        "WebDAV 配置" to "WebDAV configuration",
        "文件传输配置" to "File transfer configuration",
        "工作区微型服务器" to "Workspace mini server",
        "终端日志" to "Terminal logs",
        "终端日志读取" to "Terminal log reader",
        "系统权限" to "System permissions",
        "应用列表识别" to "App list recognition",
        "硬件检查" to "Hardware check",
        "时间感知" to "Time awareness",
        "地理感知" to "Location awareness",
        "配置管理" to "Configuration manager",
        "话题总结" to "Topic summary",
        "网页来源标注" to "Web source citation",
        "网页下载" to "Web download",
        "联网搜索" to "Web search",
        "工作区搜索" to "Workspace search",
        "读取网页" to "Read webpage",
        "读取文件" to "Read file",
        "写入文件" to "Write file",
        "追加文件" to "Append file",
        "创建目录" to "Create directory",
        "删除文件/目录" to "Delete file/directory",
        "重命名/移动" to "Rename/move",
        "列出目录" to "List directory",
        "读取文件大小、修改时间等元数据。" to "Read file metadata such as size and modified time.",
        "浏览工作目录内文件和子目录。" to "Browse files and subdirectories in the workspace.",
        "按文件名或路径片段搜索工作区。" to "Search the workspace by file name or path fragment.",
        "读取工作目录内文本文件。" to "Read text files in the workspace.",
        "创建或覆盖工作目录内文本文件。" to "Create or overwrite text files in the workspace.",
        "在现有文件末尾追加文本。" to "Append text to an existing file.",
        "在工作目录内创建文件夹。" to "Create a folder in the workspace.",
        "删除工作目录内文件或空目录。" to "Delete a file or empty folder in the workspace.",
        "调整工作目录内文件路径。" to "Move or rename a path in the workspace.",
        "全局文件搜索" to "Global file search",
        "全局列目录" to "Global list directory",
        "全局读取文件" to "Global read file",
        "全局写入文件" to "Global write file",
        "全局追加文件" to "Global append file",
        "全局创建目录" to "Global create directory",
        "全局删除文件/目录" to "Global delete file/directory",
        "全局移动/重命名" to "Global move/rename",
        "搜索 Android 共享存储中的文件路径。" to "Search file paths in Android shared storage.",
        "列出 Android 共享存储目录，支持 Download。" to "List Android shared storage directories, including Download.",
        "读取工作区外共享存储内的文本文件。" to "Read text files in shared storage outside the workspace.",
        "写入工作区外共享存储文件，执行前需要用户确认。" to "Write files in shared storage outside the workspace after confirmation.",
        "追加工作区外共享存储文件，执行前需要用户确认。" to "Append files in shared storage outside the workspace after confirmation.",
        "在工作区外共享存储创建目录，执行前需要用户确认。" to "Create directories in shared storage outside the workspace after confirmation.",
        "删除工作区外共享存储内容，执行前需要用户确认。" to "Delete shared storage content outside the workspace after confirmation.",
        "移动工作区外共享存储内容，执行前需要用户确认。" to "Move shared storage content outside the workspace after confirmation.",
        "列出 WebDAV" to "List WebDAV",
        "WebDAV 搜索" to "WebDAV search",
        "WebDAV 下载" to "WebDAV download",
        "WebDAV 上传" to "WebDAV upload",
        "WebDAV 列目录" to "WebDAV list directory",
        "查看用户已配置且启用的 WebDAV 服务器标识。" to "View configured and enabled WebDAV server identifiers.",
        "搜索 WebDAV 服务器上的文件路径。" to "Search file paths on a WebDAV server.",
        "从 WebDAV 下载文件到工作区，执行前需要用户确认。" to "Download files from WebDAV to the workspace after confirmation.",
        "把工作区文件上传到 WebDAV，执行前需要用户确认。" to "Upload workspace files to WebDAV after confirmation.",
        "通过 PROPFIND 列出 WebDAV 目录文件详情。" to "List WebDAV directory details via PROPFIND.",
        "列出文件传输服务器" to "List file transfer servers",
        "文件传输搜索" to "File transfer search",
        "文件传输下载" to "File transfer download",
        "文件传输上传" to "File transfer upload",
        "文件传输列目录" to "File transfer list directory",
        "查看用户已配置且启用的 FTP/FTPS/SFTP 服务器标识。" to "View configured and enabled FTP/FTPS/SFTP server identifiers.",
        "搜索 FTP/FTPS/SFTP 服务器上的文件路径。" to "Search file paths on FTP/FTPS/SFTP servers.",
        "从 FTP/FTPS/SFTP 下载文件到工作区，执行前需要用户确认。" to "Download files from FTP/FTPS/SFTP to the workspace after confirmation.",
        "把工作区文件上传到 FTP/FTPS/SFTP，执行前需要用户确认。" to "Upload workspace files to FTP/FTPS/SFTP after confirmation.",
        "列出 FTP/FTPS/SFTP 目录文件详情。" to "List FTP/FTPS/SFTP directory file details.",
        "列出 SSH 连接" to "List SSH connections",
        "SSH 执行命令" to "SSH command execution",
        "查看用户已配置且启用的 SSH 服务器标识。" to "View configured and enabled SSH server identifiers.",
        "登录远程服务器执行命令并返回 stdout/stderr，执行前需要用户确认。" to "Log in to a remote server, run commands, and return stdout/stderr after confirmation.",
        "Termux 配置教程" to "Termux setup guide",
        "与 Termux 通信" to "Termux communication",
        "RUN_COMMAND 权限" to "RUN_COMMAND permission",
        "请求 Root 权限" to "Request Root permission",
        "请求 Shell 权限" to "Request Shell permission",
        "Root 系统命令" to "Root system command",
        "Shell 系统命令" to "Shell system command",
        "执行命令" to "Run command",
        "通过 Termux 执行命令并返回 stdout/stderr。" to "Run commands through Termux and return stdout/stderr.",
        "读取 Skill 文件" to "Read Skill file",
        "列出 Skill 文件" to "List Skill files",
        "浏览已启用 Skill 包内文件。" to "Browse files in enabled Skill packages.",
        "读取相关 Skill 包内说明或脚本。" to "Read instructions or scripts in related Skill packages.",
        "读取会话记录" to "Read chat history",
        "搜索会话记录" to "Search chat history",
        "设置 TODO" to "Set TODO",
        "更新 TODO" to "Update TODO",
        "更新任务步骤状态。" to "Update task step status.",
        "更新清单" to "Update checklist",
        "主机/IP" to "Host/IP",
        "监听主机" to "Listen host",
        "访问用户名" to "Access username",
        "访问密码，可空" to "Access password, optional",
        "认证 Key，可空" to "Auth key, optional",
        "密码，可空" to "Password, optional",
        "用户名，可空" to "Username, optional",
        "自定义 UA，可空" to "Custom UA, optional",
        "私钥口令，可空" to "Private key passphrase, optional",
        "私钥口令（可空）" to "Private key passphrase (optional)",
        "私钥内容" to "Private key content",
        "私钥" to "Private key",
        "密码" to "Password",
        "端口" to "Port",
        "服务名" to "Service name",
        "显示名称" to "Display name",
        "备注" to "Notes",
        "编码" to "Encoding",
        "初始路径" to "Initial path",
        "远程备份路径" to "Remote backup path",
        "绑定域名：" to "Bound domains:",
        "用户名" to "Username",
        "匿名" to "Anonymous",
        "被动模式" to "Passive mode",
        "显式 FTPS" to "Explicit FTPS",
        "启用多线程传输" to "Enable multi-threaded transfer",
        "传输时同步文件权限" to "Sync file permissions during transfer",
        "在侧栏隐藏地址" to "Hide address in sidebar",
        "启用此连接" to "Enable this connection",
        "启用此服务器" to "Enable this server",
        "保存后立即启用" to "Enable immediately after save",
        "强制 HTTPS 连接" to "Force HTTPS",
        "允许目录列表" to "Allow directory listing",
        "SPA 回退到 index.html" to "SPA fallback to index.html",
        "发布 mDNS" to "Publish mDNS",
        "信任所有 HTTPS 证书" to "Trust all HTTPS certificates",
        "地址已隐藏" to "Address hidden",
        "未配置" to "Not configured",
        "未安装" to "Not installed",
        "已安装" to "Installed",
        "已授予" to "Granted",
        "已允许" to "Allowed",
        "未允许" to "Not allowed",
        "已停止" to "Stopped",
        "运行中" to "Running",
        "尚未检测" to "Not checked",
        "检测中..." to "Checking...",
        "等待检测" to "Waiting to check",
        "启动" to "Start",
        "停止服务" to "Stop service",
        "重启" to "Restart",
        "测试连接" to "Test connection",
        "测试并拉取" to "Test and fetch",
        "复制测试命令" to "Copy test command",
        "复制配置命令" to "Copy setup command",
        "点击授予" to "Tap to grant",
        "检测 Root" to "Check Root",
        "授权 Shell" to "Authorize Shell",
        "重新扫描" to "Rescan",
        "恢复预设" to "Restore preset",
        "上传证书库" to "Upload keystore",
        "上传证书链" to "Upload certificate chain",
        "上传私钥" to "Upload private key",
        "清除证书库" to "Clear keystore",
        "清空日志" to "Clear logs",
        "查看终端日志" to "View terminal logs",
        "导出备份" to "Export backup",
        "导入备份" to "Import backup",
        "导出到本地" to "Export locally",
        "从云端导入" to "Import from cloud",
        "上传备份" to "Upload backup",
        "补充导入" to "Supplement import",
        "覆盖导入" to "Overwrite import",
        "从 " to "From ",
        " 补充导入：" to " supplemental import: ",
        "导出失败: " to "Export failed: ",
        "请等待 " to "Please wait ",
        " 秒后确认删除。" to " seconds before confirming deletion.",
        "失败：" to "Failed: ",
        "状态：" to "Status: ",
        "局域网地址：" to "LAN address: ",
        "固定标识将使用 " to "Stable identifier will use ",
        "，AI 调用 SSH 工具时会使用这个标识。" to ". The AI uses this identifier when calling SSH tools.",
        " 可用 / " to " available / ",
        " 总计 · " to " total · ",
        "。音频、视频或其他文件可保存后用外部应用打开。" to ". Audio, video, and other files can be saved and opened with external apps.",
        "媒体超过 " to "Media exceeds ",
        "任务处理中 · " to "Processing · ",
        "任务耗时 · " to "Elapsed · ",
        "每天 %02d:%02d" to "Daily %02d:%02d",
        "每周%s %02d:%02d" to "Every %s %02d:%02d",
        "每月%d日 %02d:%02d" to "Monthly on day %d %02d:%02d",
        "格式：HH:mm" to "Format: HH:mm",
        "格式：yyyy-MM-dd HH:mm" to "Format: yyyy-MM-dd HH:mm",
        "超时秒数 5-300" to "Timeout seconds, 5-300",
        "默认超时秒数" to "Default timeout seconds",
        "可用" to "Available",
        "标准字" to "Standard text",
        "小字" to "Small text",
        "大字" to "Large text",
        "超大字" to "Extra large text",
        "文档" to "Document",
        "文本" to "Text",
        "代码" to "Code",
        "压缩包" to "Archive",
        "PDF 文档" to "PDF document",
        "文件" to "File",
        "未命名文件" to "Unnamed file",
        "无描述" to "No description",
        "未知" to "Unknown",
        "无法读取：" to "Unable to read: ",
        "无法读取私钥文件" to "Unable to read private key file",
        "无法读取证书库文件" to "Unable to read keystore file",
        "无法读取证书链文件" to "Unable to read certificate chain file",
        "无法打开安装器" to "Unable to open installer",
        "图片加载失败" to "Image loading failed",
        "提示词名称" to "Prompt name",
        "提示词内容" to "Prompt content",
        "示例对话（可选）" to "Example conversation (optional)",
        "编辑内置提示词" to "Edit built-in prompt",
        "编辑自定义提示词" to "Edit custom prompt",
        "提示词已保存" to "Prompt saved",
        "提示词已删除" to "Prompt deleted",
        "自定义提示词" to "Custom prompt",
        "删除 MCP" to "Delete MCP",
        "删除 SSH" to "Delete SSH",
        "删除 WebDAV" to "Delete WebDAV",
        "删除文件传输" to "Delete file transfer",
        "删除 MCP 服务器" to "Delete MCP server",
        "删除 SSH 连接" to "Delete SSH connection",
        "删除 WebDAV 配置" to "Delete WebDAV configuration",
        "删除文件传输配置" to "Delete file transfer configuration",
        "该操作会删除此 MCP 服务器连接、认证信息和已拉取的工具列表。" to "This deletes the MCP server connection, authentication, and fetched tool list.",
        "该操作会删除此 WebDAV 服务器配置和保存的认证信息。" to "This deletes the WebDAV server configuration and saved authentication.",
        "该操作会删除服务器地址、用户名、密码或私钥配置。" to "This deletes the server address, username, password, or private key configuration.",
        "删除后无法自动恢复，请确认。" to "This cannot be restored automatically. Please confirm.",
        "确认删除" to "Confirm deletion",
        "请等待" to "Please wait",
        "稍后" to "Later",
        "清理" to "Clean",
        "操作" to "Actions",
        "配置" to "Config",
        "编辑 MCP" to "Edit MCP",
        "编辑 SSH" to "Edit SSH",
        "编辑 WebDAV" to "Edit WebDAV",
        "编辑文件传输" to "Edit file transfer",
        "文件传输" to "File transfer",
        "沉浸扮演设定" to "Immersive roleplay profiles",
        "角色扮演状态" to "Roleplay status",
        "访问手机媒体文件" to "Access phone media files",
        "位置信息" to "Location",
        "通知" to "Notifications",
        "摄像头" to "Camera",
        "应用 ID" to "App ID",
        "QQ 群" to "QQ group",
        "万" to "10k",
        "亿" to "100M",
        "万亿" to "T",
        "亿亿" to "10Q",
        "一" to "Mon",
        "二" to "Tue",
        "三" to "Wed",
        "四" to "Thu",
        "五" to "Fri",
        "六" to "Sat",
        "日" to "Sun",
        " 代码" to " Code",
        " 文本" to " Text",
        " 文档" to " Document",
        " 文件" to " File",
        " 压缩包" to " Archive",
        "安装并打开 Termux，建议使用 F-Droid 或 GitHub 版本。" to "Install and open Termux. The F-Droid or GitHub version is recommended.",
        "包含 API Key / 密码 / 私钥" to "Includes API keys / passwords / private keys",
        "保护工具，不能禁用。" to "Protected tool. It cannot be disabled.",
        "本机 MCP 服务端" to "Local MCP Server",
        "本机 MCP 服务端配置已保存" to "Local MCP server settings saved",
        "本机 MCP 服务端已重启" to "Local MCP server restarted",
        "本机作为 MCP 服务端" to "Use this device as an MCP server",
        "不弹出更新提示" to "Do not show update prompts",
        "导出 CSV" to "Export CSV",
        "导出内容" to "Export content",
        "点击检测新版本" to "Tap to check for updates",
        "点击收起工具名称和简介" to "Tap to collapse tool names and descriptions",
        "点击展开查看工具名称和简介" to "Tap to expand tool names and descriptions",
        "读取 http/https 网页正文。" to "Read the body text of http/https pages.",
        "读取内置 HTTP 静态服务器状态和访问地址。" to "Read the built-in HTTP static server status and access URLs.",
        "读取设备当前时间和时区。" to "Read the current device time and time zone.",
        "读取设备最近系统定位。" to "Read the latest system location from this device.",
        "读取应用列表" to "Read app list",
        "对话历史" to "Chat history",
        "复制下面的配置命令到 Termux 执行，开启外部应用调用权限。" to "Copy the command below into Termux to enable external app calls.",
        "监听配置" to "Listen settings",
        "禁用后 AI 无法看到或调用该服务器。" to "When disabled, the AI cannot see or call this server.",
        "可使用密码或私钥连接 GitHub/GitLab 服务器、VPS、云主机或局域网主机。配置会加密保存。" to "Connect to GitHub/GitLab servers, VPSs, cloud hosts, or LAN hosts with a password or private key. Settings are encrypted.",
        "没有匹配的工具" to "No matching tools",
        "媒体、定位、通知、摄像头等权限会跳转系统应用信息页；Termux 通信权限由 Termux 提供，点击后直接弹出授权许可。" to "Media, location, notification, camera, and similar permissions open the system app info page. Termux communication permission is provided by Termux and opens its authorization prompt directly.",
        "密钥登录" to "Key login",
        "默认 su -c。可用 {command} 指定命令插入位置，例如 su 0 sh -c {command}。" to "Default: su -c. Use {command} to specify where the command is inserted, for example su 0 sh -c {command}.",
        "其他 MCP Client 可通过 http://主机:端口/mcp 连接。若监听局域网或公网，建议设置认证 Key。" to "Other MCP clients can connect through http://host:port/mcp. Set an auth key when listening on LAN or public networks.",
        "启动、停止、重启或修改工作区静态站点服务，执行前需要用户确认。" to "Start, stop, restart, or modify the workspace static site service. User confirmation is required before execution.",
        "请添加远程或局域网 MCP Server URL。若服务器使用 HTTP 明文连接，API Key 和工具参数可能被同一网络中的第三方截获。" to "Add a remote or LAN MCP Server URL. If the server uses plain HTTP, API keys and tool parameters may be intercepted by others on the same network.",
        "认证：未设置 key，局域网或公网暴露时不安全。" to "Auth: no key is set. This is unsafe on LAN or public networks.",
        "认证：已启用 Authorization Bearer / X-Lyra-MCP-Key" to "Auth: Authorization Bearer / X-Lyra-MCP-Key enabled",
        "认证方式" to "Authentication method",
        "使用密钥登录" to "Use key login",
        "使用约束" to "Usage constraints",
        "适用于 Claude 官方 Messages API 或兼容 Anthropic Messages 格式的服务。请求、工具调用和图片输入会按 Anthropic 格式转换。" to "For Claude official Messages API or services compatible with the Anthropic Messages format. Requests, tool calls, and image inputs are converted to Anthropic format.",
        "适用于 Gemini 官方 GenerateContent API 或兼容 Gemini 格式的服务。图片、音频、视频会使用 inlineData 传输。" to "For Gemini official GenerateContent API or services compatible with the Gemini format. Images, audio, and video are sent with inlineData.",
        "适用于 OpenAI Chat Completions SDK 兼容平台。原有工具调用、流式输出和多模态 image_url 路径保持不变。" to "For OpenAI Chat Completions SDK-compatible platforms. Existing tool calls, streaming, and multimodal image_url paths remain unchanged.",
        "首次使用前，请在 Termux 中开启外部应用调用权限。Termux:API 可选；未安装 Termux:API 时，Lyra Code 会使用 RunCommandService 后台静默执行命令。" to "Before first use, enable external app calls in Termux. Termux:API is optional. Without Termux:API, Lyra Code uses RunCommandService to run commands silently in the background.",
        "授权未完成，可稍后点击继续安装" to "Permission is not complete. You can tap continue installation later.",
        "搜索工具" to "Search tools",
        "搜索名称、工具名或描述" to "Search by name, tool name, or description",
        "替换证书库" to "Replace certificate store",
        "通过 Magisk、KernelSU 等 su 管理器授权。不可用时可回退到已授权的 Shell。" to "Authorize through su managers such as Magisk or KernelSU. If unavailable, it can fall back to an authorized Shell.",
        "外部 MCP Client 调用工具时，Lyra Code 默认不再弹出二次确认。请在外部 MCP Client 中配置是否需要用户确认，并避免把未设置认证 Key 的服务暴露到不可信网络。" to "When external MCP clients call tools, Lyra Code no longer shows a second confirmation by default. Configure confirmation in the external MCP client and avoid exposing services without an auth key to untrusted networks.",
        "外部调用说明" to "External call notes",
        "外部连接原始 JSON" to "External connection raw JSON",
        "复制外部连接 JSON" to "Copy external connection JSON",
        "复制配置默认只包含 Mcp-Protocol-Version 和 Authorization。X-Lyra-MCP-Key、X-API-Key、Api-Key 是兼容替代写法，不需要同时填写。请求地址必须是 /mcp。" to "The copied config only includes Mcp-Protocol-Version and Authorization by default. X-Lyra-MCP-Key, X-API-Key, and Api-Key are compatible alternatives and do not need to be filled in at the same time. The request URL must be /mcp.",
        "微型服务器控制" to "Mini server control",
        "微型服务器配置已保存" to "Mini server settings saved",
        "微型服务器状态" to "Mini server status",
        "未配置启用的 SSH 连接，工具暂不可用。" to "No enabled SSH connection is configured. The tool is unavailable.",
        "未设置认证 Key 时，同网络内能访问该端口的客户端都可请求工具调用。" to "Without an auth key, any client on the same network that can access the port may request tool calls.",
        "未授予 Termux RUN_COMMAND 权限，工具已自动禁用。" to "Termux RUN_COMMAND permission is not granted. The tool has been disabled automatically.",
        "文件传输配置已保存" to "File transfer settings saved",
        "文件信息" to "File info",
        "无法识别媒体地址：" to "Unrecognized media address: ",
        "下载文件" to "Download file",
        "下载中" to "Downloading",
        "新增" to "Add",
        "需要先通过无线调试或电脑 ADB 启动 Shizuku" to "Start Shizuku through wireless debugging or computer ADB first",
        "选择 WebDAV" to "Choose WebDAV",
        "选择内部存储下可读写的工作目录，例如 /storage/emulated/0/Fonts。" to "Choose a readable and writable workspace under internal storage, such as /storage/emulated/0/Fonts.",
        "已保存到 " to "Saved to ",
        "已导出到 Download/" to "Exported to Download/",
        "已读取私钥文件" to "Private key file loaded",
        "已读取证书库文件" to "Certificate store file loaded",
        "已读取证书链文件" to "Certificate chain file loaded",
        "已恢复预设" to "Preset restored",
        "已解码 " to "Decoded ",
        "已清空当前设定对话和好感度" to "Current character chats and affection cleared",
        "已清空联网搜索黑名单" to "Web search blacklist cleared",
        "已删除 " to "Deleted ",
        "已声明" to "Declared",
        "隐藏 URL 以避免旁人看到服务器地址。" to "Hide the URL to prevent others nearby from seeing the server address.",
        "隐藏主机地址以避免旁人看到服务器信息。" to "Hide the host address to prevent others nearby from seeing server information.",
        "应用内下载" to "In-app download",
        "用于截图反馈、排查兼容性问题，以及让硬件检查 Agent 分析当前设备环境。部分项目受系统权限和 Android 沙箱限制，可能只能显示近似信息。" to "For screenshot feedback, compatibility troubleshooting, and hardware-check Agent analysis. Some items may be approximate due to system permissions and Android sandboxing.",
        "用于连接 Git 服务器或公网 Linux/Windows 服务器。命令执行前会弹出确认。" to "Connect to Git servers or public Linux/Windows servers. Confirmation is shown before command execution.",
        "用于远程文件搜索、上传和下载；AI 执行上传下载前仍需用户确认。" to "For remote file search, upload, and download. AI uploads/downloads still require user confirmation.",
        "用于远程文件搜索、上传下载和云端备份。" to "For remote file search, upload/download, and cloud backup.",
        "原始 JSON：实际以此连接" to "Raw JSON: used for the actual connection",
        "远程 MCP 工具" to "Remote MCP tools",
        "暂无 MCP 服务器" to "No MCP servers yet",
        "暂无 SSH 连接" to "No SSH connections yet",
        "暂无 WebDAV 服务器" to "No WebDAV servers yet",
        "暂无启用的 WebDAV 服务器。先在 WebDAV 设置中添加服务器后，可直接上传或下载备份。" to "No enabled WebDAV server. Add one in WebDAV settings before uploading or downloading backups.",
        "暂无文件传输服务器" to "No file transfer servers yet",
        "站点行为" to "Site behavior",
        "正在从 WebDAV 下载并补充导入..." to "Downloading from WebDAV and importing in supplement mode...",
        "正在导出并上传 WebDAV..." to "Exporting and uploading to WebDAV...",
        "正在导出到 Download/LyraCode..." to "Exporting to Download/LyraCode...",
        "正在检查更新..." to "Checking for updates...",
        "正在启动..." to "Starting...",
        "正在清理缓存..." to "Clearing cache...",
        "支持 Streamable HTTP 与 SSE。Android 端不直接启动 stdio MCP Server。" to "Supports Streamable HTTP and SSE. Android does not start stdio MCP Servers directly.",
        "智能刷新率" to "Adaptive refresh rate",
        "重新打开 Lyra Code，在设置的应用权限页面授予 RUN_COMMAND 权限。" to "Reopen Lyra Code and grant RUN_COMMAND permission on the App permissions settings page.",
        "主机" to "Host",
        "字体跟随系统" to "Font follows system",
        "自定义 su 命令" to "Custom su command",
        "自动跟随连接、资源加载、认证失败、404 和页面 JavaScript 报错。" to "Automatically follows connections, resource loading, authentication failures, 404s, and page JavaScript errors.",
        "总占用按 Android 设置页常见口径估算：安装包 + 应用数据 + 缓存。清理范围仅包含临时上传、图片裁剪、拍照预览和 AI 响应磁盘缓存；不会删除历史对话、模型配置、API Key、MCP/SSH、Skills、头像或工作目录文件。" to "Total usage is estimated like Android Settings: APK + app data + cache. Cleanup only includes temporary uploads, image crops, camera previews, and AI response disk cache. It will not delete chat history, model settings, API keys, MCP/SSH, Skills, avatars, or workspace files.",
        "最近结果：" to "Latest result: ",
        "最近失败：" to "Latest failure: ",
        "AI 使用 SSH 执行命令会像文件修改一样请求确认。安装软件或修改服务器前，AI 应先检查系统、CPU/GPU、内存、磁盘和权限。复杂交互式 shell（如 vim/top/交互 ssh）不适合由内置 SSH 工具执行。" to "AI SSH commands request confirmation just like file modifications. Before installing software or changing servers, the AI should check the system, CPU/GPU, memory, disk, and permissions. Complex interactive shells such as vim, top, or interactive ssh are not suitable for the built-in SSH tool.",
        "API Key 保存在本机配置中；对话、工具输出、缓存和审查日志默认留在本机。使用第三方模型接口、HTTP 明文 URL、联网搜索、MCP 或 Termux 命令时，数据会按用户配置发送到对应服务或本机执行环境。" to "API keys are stored in local settings. Chats, tool outputs, caches, and review logs stay on this device by default. When using third-party model APIs, plain HTTP URLs, web search, MCP, or Termux commands, data is sent to the configured service or local execution environment.",
        "HTTP 明文连接不安全，但不会阻止添加。" to "Plain HTTP is unsafe, but adding it is not blocked.",
        "HTTP 明文连接不安全，可能泄露账号密码和文件内容。" to "Plain HTTP is unsafe and may expose accounts, passwords, and file contents.",
        "HTTPS 证书" to "HTTPS certificate",
        "MCP 服务器已保存" to "MCP server saved",
        "mDNS 名称" to "mDNS name",
        "No backup 数据" to "No backup data",
        "Root 和 Shell 开关都关闭时，AI 不会看到任何系统命令工具。所有 Shell/Root 命令都会先显示完整命令并请求确认；Root 命令风险更高。普通 ADB 不会永久赋予应用 shell 身份，本应用通过 Shizuku 获取该能力。" to "When both Root and Shell are off, the AI cannot see any system command tools. All Shell/Root commands show the full command and request confirmation first. Root commands are higher risk. Normal ADB does not permanently grant shell identity to apps; this app obtains that ability through Shizuku.",
        "Root 可用" to "Root available",
        "Shell 已授权" to "Shell authorized",
        "Shizuku 正在运行，开启后请求授权" to "Shizuku is running. Enable it to request authorization.",
        "Shizuku Shell 已授权" to "Shizuku Shell authorized",
        "SSH 连接已保存" to "SSH connection saved",
        "SSH 连接与远程命令执行。" to "SSH connections and remote command execution.",
        "WebDAV 已保存" to "WebDAV saved",
        "WebDAV 云备份" to "WebDAV cloud backup",        )

    private fun translateBySegments(text: String): String {
        if (!text.any { it in '\u4e00'..'\u9fff' }) return text
        var result = text
        for ((from, to) in segmentTranslations.sortedByDescending { it.first.length }) {
            result = result.replace(from, to)
        }
        return if (result.any { it in '\u4e00'..'\u9fff' }) text else result
    }

    private fun translateDynamic(text: String): String {
        val t = text.trim()
        return when {
            t.startsWith("已导入 ") -> "Imported " + t.removePrefix("已导入 ")
            t.startsWith("已添加表情 ") -> "Sticker added " + t.removePrefix("已添加表情 ")
            t.startsWith("已删除 ") -> "Deleted " + t.removePrefix("已删除 ")
            t.startsWith("好感度：") -> t.replace("好感度：", "Affection: ").replace(" 个文件", " files")
            t.startsWith("好感度 ") -> t.replace("好感度", "Affection")
            t.endsWith(" 个模型") -> t.replace(" 个模型", " models")
            t.startsWith("已获取 ") && t.endsWith(" 个模型") -> t.replace("已获取 ", "Fetched ").replace(" 个模型", " models")
            t.startsWith("当前将保存 ") && t.endsWith(" 个域名") -> t.replace("当前将保存 ", "Will save ").replace(" 个域名", " domains")
            t.startsWith("蒙版透明度 ") -> t.replace("蒙版透明度", "Mask opacity")
            t.startsWith("下次执行：") -> t.replace("下次执行：", "Next run: ")
            t.startsWith("最近失败：") -> t.replace("最近失败：", "Last failure: ")
            t.startsWith("最近结果：") -> t.replace("最近结果：", "Last result: ")
            t.startsWith("确定删除“") -> t
                .replace("确定删除“", "Delete \"")
                .replace("”吗？", "\"? ")
                .replace("该操作不会删除原模型服务。", "This will not delete the original model service.")
            t.startsWith("正在执行子代理任务") -> t.replace("正在执行子代理任务", "Running sub-agent task")
            t.startsWith("状态：") -> t
                .replace("状态：", "Status: ")
                .replace("频率：", "Schedule: ")
                .replace("模型：", "Model: ")
                .replace("最近执行：", "Last run: ")
                .replace("尚未执行", "Not run yet")
            t.startsWith("执行频率：") -> t.replace("执行频率：", "Frequency: ")
            t.startsWith("服务商：") -> t.replace("服务商：", "Provider: ")
            t.startsWith("已保存到 ") -> t.replace("已保存到 ", "Saved to ")
            t.startsWith("已解码 ") -> t.replace("已解码 ", "Decoded ").replace("。音频、视频或其他文件可保存后用外部应用打开。", ". Audio, video, and other files can be saved and opened with another app.")
            t.startsWith("无法识别媒体地址：") -> t.replace("无法识别媒体地址：", "Unrecognized media URL: ")
            t.startsWith("工具返回 ") -> t.replace("工具返回 ", "Tool returned ").replace(" 字符：", " characters: ")
            t.startsWith("已截断预览，完整工具结果共 ") -> t.replace("已截断预览，完整工具结果共 ", "Preview truncated. Full tool result has ").replace(" 字符。", " characters.")
            t.endsWith("小时") || t.endsWith("分") || t.endsWith("秒") -> t.replace("小时", "h ").replace("分", "m ").replace("秒", "s")
            else -> text
        }
    }
}

internal fun uiText(text: String): String = UiTextBridge.translate(text)








